language: java
jdk:
- openjdk11
addons:
  sonarcloud:
    organization: lorescianatico-github
    token:
      secure: s29LqkuXdW3q8c20jWQC/ez/I2QnyefR6Tnt1+FGeGXqHSjL057WM3lE8HGruc9xFk0EaX5zLNmQpVz/pDRY9z2Bm6+xPi/eMiRYGpHJgYsBfM58Zkoyq/3H7iRIK6zZGi+PO8pnA06vsK7c577Pj0YzNSEB7laG13p05IULUv03eFWZjNN8MXBYN8MvjuMNNYimHD2tYZyN8NDt7tw3j72nQhXyeAoPEBITQ7Kmbr4KuZ146SunBpsD7WFkTUtrwkmRcQFrXWCSwioZ/4Ufuaq2QopYhAdSCADV3bz9cJ3oxmxhbczsEnNb1y4NkoUof+mlqjht9KT5/AZJ8QWIyA+P7NXZK7Z+k+SpGz6KNLLvn1UtHPwud5oSZlQ7ZeonfZEhlWMDIUhzJm/W/fSeyAYvtAsBctKupmRhv3Hr5k+8dNqMaZ0mZJOoXoFayyrSUs+anJGjcgG4BqUe+ewP6Nc6zDm5NHNFOwvQ1HxIt+I8OIrkDyqxiiOT2r2U2mbicN1bwTWCIPRefxUMrnT7ZO3pGbH2ifRTKJ4HU27XDUoJS9ptZZiXsiXwg74SXbJrxaZYZdNSqfwsGTM9R306E250EYkhkVY67uAW1ULGZ60mwgGsuOSA4Ejj8DyhZbxTLqSfhbe4BE3EuisNjiFYSTW/oW+5LsadqY8dwQUN0EI=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=LoreScianatico_SpringPatterns